# Setup
title:               Quantitative Market Intelligence
tagline:             '2020-2021'
url:                 'https://quantitativemarketintel.github.io/'
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              QMI Directors <3
  url:               http://usitquant.com
  email:             jessica@usitquant.org

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
